'use client';

import { ThemeProvider } from 'next-themes';
import './globals.css';
import { Roboto } from 'next/font/google';
import { PropsWithChildren } from 'react';
import Header from '@/components/header/Header';

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    fallback: ['Helvetica', 'Arial', 'sans-serif'],
});

export const metadata = {
    title: 'My Blogger',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body className="bg-white dark:bg-dark-mode">
                <ThemeProvider attribute="class">
                    <Header />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
